package com.example.hugbo_team_13.persistence.entity;


import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;


/**
 * Entity class representing an event in the application.
 * Mapped to the "event" table in the database.
 */
@Entity
@Table(name = "event")
@Getter
@Setter
@NoArgsConstructor
public class EventEntity {

    /**
     * Unique identifier for the event.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * The name of the event.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The start date and time of the event.
     * Cannot be null.
     */
    @Column(nullable = false)
    private LocalDateTime startDateTime;

    /**
     * The end date and time of the event.
     * Cannot be null.
     */
    @Column(nullable = false)
    private LocalDateTime endDateTime;
}
